Repository zippick/zippick-backend, pull requests merged in 2025-07, with the labels that each got.

#2 refactor: 폴더 구조 변경 및 테스트용 파일 삭제
  zippick/src/main/java/zippick/controller/HelloController.java
  zippick/src/main/java/zippick/global/config/CorsConfig.java
  zippick/src/main/java/zippick/global/config/OpenApiConfig.java
  zippick/src/main/java/zippick/global/config/S3Config.java
  zippick/src/main/java/zippick/mapper/Mapper.java
Labels: documentation

#13 feat : AI 합성 및 Product 조회 관련 API
  .github/workflows/deploy.yml
  zippick/build.gradle
  zippick/src/main/java/zippick/domain/member/controller/MemberController.java
  zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
  zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
  zippick/src/main/java/zippick/domain/member/service/MemberService.java
  zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
  zippick/src/main/java/zippick/domain/product/controller/ProductController.java
  zippick/src/main/java/zippick/domain/product/dto/request/AiComposeRequest.java
  zippick/src/main/java/zippick/domain/product/dto/response/AiComposeResponse.java
  zippick/src/main/java/zippick/domain/product/dto/response/ProductDto.java
  zippick/src/main/java/zippick/domain/product/dto/response/ProductResponse.java
  zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
  zippick/src/main/java/zippick/domain/product/model/FurnitureCategory.java
  zippick/src/main/java/zippick/domain/product/service/ProductService.java
  zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
  zippick/src/main/java/zippick/global/config/CorsConfig.java
  zippick/src/main/java/zippick/global/config/OpenApiConfig.java
  zippick/src/main/java/zippick/global/config/S3Config.java
  zippick/src/main/java/zippick/global/exception/ErrorCode.java
  zippick/src/main/java/zippick/infra/file/s3/S3Uploader.java
  zippick/src/main/java/zippick/member/service/MemberService.java
  zippick/src/main/resources/application.yml
  zippick/src/main/resources/mapper/member/MemberMapper.xml
  zippick/src/main/resources/mapper/product/ProductMapper.xml
  zippick/src/test/java/zippick/S3UploadTest.java
Labels: feat

#18 feat: 로그인 로그아웃 필터
  zippick/build.gradle
  zippick/src/main/java/zippick/domain/auth/controller/AuthController.java
  zippick/src/main/java/zippick/domain/auth/dto/AuthTokenDTO.java
  zippick/src/main/java/zippick/domain/auth/dto/request/LoginRequest.java
  zippick/src/main/java/zippick/domain/auth/dto/response/LoginResponse.java
  zippick/src/main/java/zippick/domain/auth/mapper/AuthMapper.java
  zippick/src/main/java/zippick/domain/auth/service/AuthService.java
  zippick/src/main/java/zippick/domain/auth/service/AuthServiceImpl.java
  zippick/src/main/java/zippick/domain/member/controller/MemberController.java
  zippick/src/main/java/zippick/domain/member/dto/MemberDTO.java
  zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
  zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
  zippick/src/main/java/zippick/domain/member/service/MemberService.java
  zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
  zippick/src/main/java/zippick/global/config/FilterConfig.java
  zippick/src/main/java/zippick/global/config/SecurityConfig.java
  zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
  zippick/src/main/resources/mapper/auth/AuthMapper.xml
Labels: enhancement

#21 [FEAT] 스웨거 인증 추가
  zippick/src/main/java/zippick/global/config/OpenApiConfig.java
Labels: feat

#22 feat: 내 정보 조회
  zippick/src/main/java/zippick/domain/member/controller/MemberController.java
  zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
  zippick/src/main/java/zippick/domain/member/dto/response/MyInfoResponse.java
  zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
  zippick/src/main/java/zippick/domain/member/service/MemberService.java
  zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
  zippick/src/main/java/zippick/global/exception/ErrorCode.java
  zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
  zippick/src/main/resources/mapper/member/MemberMapper.xml
Labels: enhancement

#28 [REFACTOR] 사이즈 기반 검색시 카테고리 추가
  zippick/src/main/java/zippick/domain/product/controller/ProductController.java
  zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
  zippick/src/main/java/zippick/domain/product/service/ProductService.java
  zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
  zippick/src/main/resources/mapper/product/ProductMapper.xml
Labels: enhancement

#31 feat: 이메일 중복 확인
  zippick/src/main/java/zippick/domain/member/controller/MemberController.java
  zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
  zippick/src/main/java/zippick/domain/member/service/MemberService.java
  zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
  zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
  zippick/src/main/resources/mapper/member/MemberMapper.xml
Labels: feat

#40 [FEAT] AI 기반 이미지 분석 구현
  zippick/src/main/java/zippick/domain/product/controller/ProductController.java
  zippick/src/main/java/zippick/domain/product/dto/response/InteriorAnalysisResponse.java
  zippick/src/main/java/zippick/domain/product/service/ProductService.java
  zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
Labels: feat

#54 이미지 분석 기반 상품 필터링 구현
  zippick/src/main/java/zippick/domain/product/controller/ProductController.java
  zippick/src/main/java/zippick/domain/product/dto/request/AiRecommendRequest.java
  zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
  zippick/src/main/java/zippick/domain/product/service/ProductService.java
  zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
  zippick/src/main/resources/mapper/product/ProductMapper.xml
Labels: feat

#67 bug: 데이터 타입 수정
  zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
Labels: bug
